In [1]:
import pandas as pd

In [8]:
from datetime import date
from interactive_data_loader import load_kalshi_market
# Load market snapshots for a specific date range
df_market = load_kalshi_market(
    start_date=date(2021, 2, 20), 
    end_date=date(2030, 2, 22)
)

In [9]:
df_market.tail()

,snapshot_ts,event_ticker,market_ticker,subtitle,yes_bid,yes_ask,no_bid,no_ask,last_price,volume,open_interest,trigger
532978,2026-02-25 04:30:37.373702+00:00,KXHIGHAUS-26FEB24,KXHIGHAUS-26FEB24-T73,72° or below,0,1,99,100,4,35080,26114,periodic
532979,2026-02-25 04:30:37.373702+00:00,KXHIGHAUS-26FEB24,KXHIGHAUS-26FEB24-T80,81° or above,0,1,99,100,1,11478,9770,periodic
532980,2026-02-25 04:30:37.373702+00:00,KXHIGHAUS-26FEB24,KXHIGHAUS-26FEB24-B77.5,77° to 78°,0,1,99,100,29,52202,24696,periodic
532981,2026-02-25 04:30:37.373702+00:00,KXHIGHAUS-26FEB24,KXHIGHAUS-26FEB24-B73.5,73° to 74°,0,1,99,100,16,41776,25246,periodic
532982,2026-02-25 04:30:37.373702+00:00,KXHIGHAUS-26FEB24,KXHIGHAUS-26FEB24-B75.5,75° to 76°,99,100,0,1,52,73034,29162,periodic

In [4]:
from datetime import date
from interactive_data_loader import load_nwp_data
# Valid models: 'hrrr', 'nbm', 'rrfs'
df_hrrr = load_nwp_data(
    model="hrrr", 
    start_date=date(2021, 2, 20),
)

In [5]:
df_hrrr

,station,city,model,cycle_utc,forecast_minutes,valid_utc,tmp_2m_k,tmp_2m_f,grid_lat,grid_lon,valid_local,notification_ts,saved_ts,notification_latency_s,total_latency_s,ingest_latency_s
0,KMDW,Chicago,hrrr,2026-02-23 02:00:00+00:00,495,2026-02-23 10:15:00+00:00,265.260000,17.800000,41.7809,-87.7722,2026-02-23 04:15:00,2026-02-23 03:08:52.040000+00:00,2026-02-23 03:08:53.623324+00:00,4132.0,4133.6,1.6
1,KMDW,Chicago,hrrr,2026-02-23 02:00:00+00:00,510,2026-02-23 10:30:00+00:00,265.150000,17.600000,41.7809,-87.7722,2026-02-23 04:30:00,2026-02-23 03:08:52.040000+00:00,2026-02-23 03:08:53.623324+00:00,4132.0,4133.6,1.6
2,KMDW,Chicago,hrrr,2026-02-23 02:00:00+00:00,525,2026-02-23 10:45:00+00:00,265.100000,17.500000,41.7809,-87.7722,2026-02-23 04:45:00,2026-02-23 03:08:52.040000+00:00,2026-02-23 03:08:53.623324+00:00,4132.0,4133.6,1.6
3,KMDW,Chicago,hrrr,2026-02-23 02:00:00+00:00,540,2026-02-23 11:00:00+00:00,265.050000,17.400000,41.7809,-87.7722,2026-02-23 05:00:00,2026-02-23 03:08:52.040000+00:00,2026-02-23 03:08:53.623324+00:00,4132.0,4133.6,1.6
4,KMDW,Chicago,hrrr,2026-02-23 02:00:00+00:00,555,2026-02-23 11:15:00+00:00,264.940000,17.200000,41.7809,-87.7722,2026-02-23 05:15:00,2026-02-23 03:19:36.773000+00:00,2026-02-23 03:19:37.630452+00:00,4776.8,4777.6,0.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3593,KMDW,Chicago,hrrr,2026-02-25 03:00:00+00:00,1020,2026-02-25 20:00:00+00:00,274.450470,34.340846,41.7809,-87.7722,2026-02-25 14:00:00,2026-02-25 04:23:37.387000+00:00,2026-02-25 04:23:38.168018+00:00,5017.4,5018.2,0.8
3594,KMDW,Chicago,hrrr,2026-02-25 03:00:00+00:00,1035,2026-02-25 20:15:00+00:00,274.587585,34.587654,41.7809,-87.7722,2026-02-25 14:15:00,2026-02-25 04:33:37.730000+00:00,2026-02-25 04:33:38.592756+00:00,5617.7,5618.6,0.9
3595,KMDW,Chicago,hrrr,2026-02-25 03:00:00+00:00,1050,2026-02-25 20:30:00+00:00,274.670807,34.737452,41.7809,-87.7722,2026-02-25 14:30:00,2026-02-25 04:33:37.730000+00:00,2026-02-25 04:33:38.592756+00:00,5617.7,5618.6,0.9
3596,KMDW,Chicago,hrrr,2026-02-25 03:00:00+00:00,1065,2026-02-25 20:45:00+00:00,274.746399,34.873518,41.7809,-87.7722,2026-02-25 14:45:00,2026-02-25 04:33:37.730000+00:00,2026-02-25 04:33:38.592756+00:00,5617.7,5618.6,0.9
3597,KMDW,Chicago,hrrr,2026-02-25 03:00:00+00:00,1080,2026-02-25 21:00:00+00:00,274.769684,34.915431,41.7809,-87.7722,2026-02-25 15:00:00,2026-02-25 04:33:37.730000+00:00,2026-02-25 04:33:38.592756+00:00,5617.7,5618.6,0.9