In [1]:
import pandas as pd

In [18]:
from datetime import date
from interactive_data_loader import load_kalshi_market
# Load market snapshots for a specific date range
df_market = load_kalshi_market(
    start_date=date(2021, 2, 20), 
    end_date=date(2030, 2, 22)
)

In [19]:
df_market.tail()

,snapshot_ts_utc,event_ticker,market_ticker,subtitle,yes_bid,yes_ask,no_bid,no_ask,last_price,volume,open_interest,trigger,is_data_live
764878,2026-02-27 20:21:52.518845+00:00,KXHIGHAUS-26FEB27,KXHIGHAUS-26FEB27-T83,82° or below,0.0,1.0,99.0,100.0,1.0,16972.0,11450.0,periodic,True
764879,2026-02-27 20:21:52.518845+00:00,KXHIGHAUS-26FEB27,KXHIGHAUS-26FEB27-T90,91° or above,0.0,1.0,99.0,100.0,1.0,14194.0,11496.0,periodic,True
764880,2026-02-27 20:21:52.518845+00:00,KXHIGHAUS-26FEB27,KXHIGHAUS-26FEB27-B89.5,89° to 90°,9.0,12.0,88.0,91.0,9.0,25498.0,17410.0,periodic,True
764881,2026-02-27 20:21:52.518845+00:00,KXHIGHAUS-26FEB27,KXHIGHAUS-26FEB27-B85.5,85° to 86°,25.0,30.0,70.0,75.0,24.0,40324.0,20868.0,periodic,True
764882,2026-02-27 20:21:52.518845+00:00,KXHIGHAUS-26FEB27,KXHIGHAUS-26FEB27-B87.5,87° to 88°,69.0,74.0,26.0,31.0,66.0,46776.0,28716.0,periodic,True

In [20]:
from datetime import date
from interactive_data_loader import load_kalshi_orderbook
# Load orderbook snapshots for a specific date range
# By default, reconstruct=True which builds the full limit order book
df_orderbook = load_kalshi_orderbook(
    start_date=date(2021, 2, 20), 
    end_date=date(2030, 2, 22)
)

In [21]:
df_orderbook.head()

,snapshot_ts_utc,market_ticker,side,price_cents,quantity,snapshot_type,is_data_live
0,2026-02-19 03:40:10.443637+00:00,KXHIGHCHI-26FEB19-B61.5,yes,2.0,59.0,reconstructed,True
1,2026-02-19 03:40:10.443637+00:00,KXHIGHCHI-26FEB19-B61.5,yes,1.0,258.0,reconstructed,True
2,2026-02-19 03:40:10.443637+00:00,KXHIGHCHI-26FEB19-B61.5,no,91.0,3.0,reconstructed,True
3,2026-02-19 03:40:10.443637+00:00,KXHIGHCHI-26FEB19-B61.5,no,94.0,7.0,reconstructed,True
4,2026-02-19 03:40:10.443637+00:00,KXHIGHCHI-26FEB19-B61.5,no,95.0,326.0,reconstructed,True

In [22]:
from datetime import date
from interactive_data_loader import load_nwp_data
# Valid models: 'hrrr', 'nbm', 'rrfs'
df_hrrr = load_nwp_data(
    model="nbm", 
    start_date=date(2021, 2, 20),
)

In [30]:
from datetime import date
from interactive_data_loader import load_wethr_push

# `observations`, `dsm`, `cli`, `new_high`, `new_low`.

event_type = "observations"
station_icao = "KMDW"
target_date =date(2026, 2, 20)

obs = load_wethr_push(event_type, station=station_icao, start_date=target_date)

In [32]:
obs.dtypes

station_code                           object
observation_time_utc      datetime64[ns, UTC]
received_ts_utc           datetime64[ns, UTC]
live                                     bool
product                                object
temperature_celsius                   float64
temperature_fahrenheit                float64
dew_point_celsius                     float64
dew_point_fahrenheit                  float64
relative_humidity                     float64
wind_direction                         object
wind_speed_mph                        float64
wind_gust_mph                         float64
visibility_miles                      float64
altimeter_inhg                        float64
wethr_high_nws_f                      float64
wethr_high_wu_f                        object
wethr_low_nws_f                       float64
wethr_low_wu_f                         object
anomaly                                  bool
event_id                               object
observation_time_lst           datetime64[ns]
observation_date_lst           datetime64[ns]
dtype: object

In [41]:
obs['wethr_high_nws_f'].isna().sum()

np.int64(1176)

In [34]:
obs.head(2000)[['station_code','observation_time_utc', 'observation_time_lst','temperature_fahrenheit','wethr_high_nws_f']].head()

,station_code,observation_time_utc,observation_time_lst,temperature_fahrenheit,wethr_high_nws_f
0,KMDW,2026-02-25 00:00:00+00:00,2026-02-24 18:00:00,37.4,NaN
1,KMDW,2026-02-25 00:05:00+00:00,2026-02-24 18:05:00,37.4,NaN
2,KMDW,2026-02-25 00:10:00+00:00,2026-02-24 18:10:00,37.4,NaN
3,KMDW,2026-02-25 00:15:00+00:00,2026-02-24 18:15:00,37.4,NaN
4,KMDW,2026-02-25 00:20:00+00:00,2026-02-24 18:20:00,39.2,NaN

In [36]:
from datetime import date
from interactive_data_loader import load_wethr_push

# `observations`, `dsm`, `cli`, `new_high`, `new_low`.

event_type = "dsm"
station_icao = "KMDW"
target_date =date(2021, 2, 20)

cli = load_wethr_push(event_type, station=station_icao, start_date=target_date)

In [37]:
cli

,station_code,for_date,received_ts_utc,live,high_f,high_c,high_time_utc,low_f,low_c,low_time_utc,anomaly,event_id
0,KMDW,2026-02-25,2026-02-25 20:06:00+00:00,False,38.0,3.33,NaT,None,None,NaT,False,159987930
1,KMDW,2026-02-26,2026-02-26 21:02:00+00:00,False,40.0,4.44,NaT,None,None,NaT,False,162902121
2,KMDW,2026-02-26,2026-02-26 22:02:00+00:00,False,42.0,5.56,NaT,None,None,NaT,False,163023445
3,KMDW,2026-02-27,2026-02-27 21:02:00+00:00,False,64.0,17.78,NaT,None,None,NaT,False,165893271
4,KMDW,2026-02-27,2026-02-27 22:02:00+00:00,False,65.0,18.33,NaT,None,None,NaT,False,166019462