In [1]:
import pandas as pd

In [10]:
from datetime import date
from interactive_data_loader import load_kalshi_market
# Load market snapshots for a specific date range
df_market = load_kalshi_market(
    start_date=date(2021, 2, 20), 
    end_date=date(2030, 2, 22)
)

In [11]:
df_market.tail()

,snapshot_ts_utc,event_ticker,market_ticker,subtitle,yes_bid,yes_ask,no_bid,no_ask,last_price,volume,open_interest,trigger,is_data_live
764878,2026-02-27 20:21:52.518845+00:00,KXHIGHAUS-26FEB27,KXHIGHAUS-26FEB27-T83,82° or below,0.0,1.0,99.0,100.0,1.0,16972.0,11450.0,periodic,True
764879,2026-02-27 20:21:52.518845+00:00,KXHIGHAUS-26FEB27,KXHIGHAUS-26FEB27-T90,91° or above,0.0,1.0,99.0,100.0,1.0,14194.0,11496.0,periodic,True
764880,2026-02-27 20:21:52.518845+00:00,KXHIGHAUS-26FEB27,KXHIGHAUS-26FEB27-B89.5,89° to 90°,9.0,12.0,88.0,91.0,9.0,25498.0,17410.0,periodic,True
764881,2026-02-27 20:21:52.518845+00:00,KXHIGHAUS-26FEB27,KXHIGHAUS-26FEB27-B85.5,85° to 86°,25.0,30.0,70.0,75.0,24.0,40324.0,20868.0,periodic,True
764882,2026-02-27 20:21:52.518845+00:00,KXHIGHAUS-26FEB27,KXHIGHAUS-26FEB27-B87.5,87° to 88°,69.0,74.0,26.0,31.0,66.0,46776.0,28716.0,periodic,True

In [12]:
from datetime import date
from interactive_data_loader import load_kalshi_orderbook
# Load orderbook snapshots for a specific date range
# By default, reconstruct=True which builds the full limit order book
df_orderbook = load_kalshi_orderbook(
    start_date=date(2021, 2, 20), 
    end_date=date(2030, 2, 22)
)

In [13]:
df_orderbook.head()

,snapshot_ts_utc,market_ticker,side,price_cents,quantity,snapshot_type,is_data_live
0,2026-02-19 03:40:10.443637+00:00,KXHIGHCHI-26FEB19-B61.5,yes,2.0,59.0,reconstructed,True
1,2026-02-19 03:40:10.443637+00:00,KXHIGHCHI-26FEB19-B61.5,yes,1.0,258.0,reconstructed,True
2,2026-02-19 03:40:10.443637+00:00,KXHIGHCHI-26FEB19-B61.5,no,91.0,3.0,reconstructed,True
3,2026-02-19 03:40:10.443637+00:00,KXHIGHCHI-26FEB19-B61.5,no,94.0,7.0,reconstructed,True
4,2026-02-19 03:40:10.443637+00:00,KXHIGHCHI-26FEB19-B61.5,no,95.0,326.0,reconstructed,True

In [16]:
from datetime import date
from interactive_data_loader import load_nwp_data
# Valid models: 'hrrr', 'nbm', 'rrfs'
df_hrrr = load_nwp_data(
    model="nbm", 
    start_date=date(2021, 2, 20),
)

In [17]:
df_hrrr

,station,city,model,cycle_utc,forecast_minutes,valid_utc,tmp_2m_k,tmp_2m_f,grid_lat,grid_lon,valid_local,notification_ts,saved_ts,notification_latency_s,total_latency_s,ingest_latency_s
0,KMDW,Chicago,nbm,2026-02-27 04:00:00+00:00,8760,2026-03-05 06:00:00+00:00,317.15,111.2,41.7941,-87.7401,2026-03-05 00:00:00,2026-02-27 04:49:13.622000+00:00,2026-02-27 04:50:08.311341+00:00,2953.6,3008.3,54.7
1,KMDW,Chicago,nbm,2026-02-27 05:00:00+00:00,4020,2026-03-02 00:00:00+00:00,302.15,84.2,41.7941,-87.7401,2026-03-01 18:00:00,2026-02-27 05:46:35.167000+00:00,2026-02-27 05:47:36.583536+00:00,2795.2,2856.6,61.4
2,KMDW,Chicago,nbm,2026-02-27 06:00:00+00:00,480,2026-02-27 14:00:00+00:00,309.15,96.8,41.7941,-87.7401,2026-02-27 08:00:00,2026-02-27 06:46:37.516000+00:00,2026-02-27 06:47:23.508574+00:00,2797.5,2843.5,46.0
3,KMDW,Chicago,nbm,2026-02-27 06:00:00+00:00,720,2026-02-27 18:00:00+00:00,327.15,129.2,41.7941,-87.7401,2026-02-27 12:00:00,2026-02-27 06:46:37.580000+00:00,2026-02-27 06:47:23.290109+00:00,2797.6,2843.3,45.7
4,KMDW,Chicago,nbm,2026-02-27 06:00:00+00:00,840,2026-02-27 20:00:00+00:00,331.15,136.4,41.7941,-87.7401,2026-02-27 14:00:00,2026-02-27 06:46:37.547000+00:00,2026-02-27 06:47:24.575605+00:00,2797.5,2844.6,47.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,KMDW,Chicago,nbm,2026-02-27 17:00:00+00:00,14100,2026-03-09 12:00:00+00:00,318.15,113.0,41.7941,-87.7401,2026-03-09 07:00:00,2026-02-27 17:46:27.153000+00:00,2026-02-27 17:47:20.886139+00:00,2787.2,2840.9,53.7
193,KMDW,Chicago,nbm,2026-02-27 18:00:00+00:00,1200,2026-02-28 14:00:00+00:00,305.15,89.6,41.7941,-87.7401,2026-02-28 08:00:00,2026-02-27 18:46:42.703000+00:00,2026-02-27 18:47:23.090716+00:00,2802.7,2843.1,40.4
194,KMDW,Chicago,nbm,2026-02-27 18:00:00+00:00,3060,2026-03-01 21:00:00+00:00,303.15,86.0,41.7941,-87.7401,2026-03-01 15:00:00,2026-02-27 18:46:42.739000+00:00,2026-02-27 18:47:23.409041+00:00,2802.7,2843.4,40.7
195,KMDW,Chicago,nbm,2026-02-27 18:00:00+00:00,9000,2026-03-06 00:00:00+00:00,324.15,123.8,41.7941,-87.7401,2026-03-05 18:00:00,2026-02-27 18:46:43.507000+00:00,2026-02-27 18:47:23.739895+00:00,2803.5,2843.7,40.2
196,KMDW,Chicago,nbm,2026-02-27 18:00:00+00:00,12960,2026-03-08 18:00:00+00:00,322.15,120.2,41.7941,-87.7401,2026-03-08 13:00:00,2026-02-27 18:46:44.263000+00:00,2026-02-27 18:47:24.026943+00:00,2804.3,2844.0,39.8

In [ ]:
from datetime import date
from interactive_data_loader import load_nwp_data