In [1]:
import pandas as pd

In [20]:
from datetime import date
from interactive_data_loader import load_kalshi_market
# Load market snapshots for a specific date range
df_market = load_kalshi_market(
    start_date=date(2021, 2, 20), 
    end_date=date(2030, 2, 22)
)

In [21]:
df_market.tail()

,snapshot_ts_utc,event_ticker,market_ticker,subtitle,yes_bid,yes_ask,no_bid,no_ask,last_price,volume,open_interest,trigger
532978,2026-02-25 04:30:37.373702+00:00,KXHIGHAUS-26FEB24,KXHIGHAUS-26FEB24-T73,72° or below,0,1,99,100,4,35080,26114,periodic
532979,2026-02-25 04:30:37.373702+00:00,KXHIGHAUS-26FEB24,KXHIGHAUS-26FEB24-T80,81° or above,0,1,99,100,1,11478,9770,periodic
532980,2026-02-25 04:30:37.373702+00:00,KXHIGHAUS-26FEB24,KXHIGHAUS-26FEB24-B77.5,77° to 78°,0,1,99,100,29,52202,24696,periodic
532981,2026-02-25 04:30:37.373702+00:00,KXHIGHAUS-26FEB24,KXHIGHAUS-26FEB24-B73.5,73° to 74°,0,1,99,100,16,41776,25246,periodic
532982,2026-02-25 04:30:37.373702+00:00,KXHIGHAUS-26FEB24,KXHIGHAUS-26FEB24-B75.5,75° to 76°,99,100,0,1,52,73034,29162,periodic

In [10]:
from datetime import date
from interactive_data_loader import load_kalshi_orderbook
# Load orderbook snapshots for a specific date range
# By default, reconstruct=True which builds the full limit order book
df_orderbook = load_kalshi_orderbook(
    start_date=date(2021, 2, 20), 
    end_date=date(2030, 2, 22)
)

In [11]:
df_orderbook.head()

,snapshot_ts,market_ticker,side,price_cents,quantity,snapshot_type
0,2026-02-19 03:40:10.443637+00:00,KXHIGHCHI-26FEB19-B61.5,yes,2,59.0,reconstructed
1,2026-02-19 03:40:10.443637+00:00,KXHIGHCHI-26FEB19-B61.5,yes,1,258.0,reconstructed
2,2026-02-19 03:40:10.443637+00:00,KXHIGHCHI-26FEB19-B61.5,no,91,3.0,reconstructed
3,2026-02-19 03:40:10.443637+00:00,KXHIGHCHI-26FEB19-B61.5,no,94,7.0,reconstructed
4,2026-02-19 03:40:10.443637+00:00,KXHIGHCHI-26FEB19-B61.5,no,95,326.0,reconstructed

In [16]:
from datetime import date
from interactive_data_loader import load_nwp_data
# Valid models: 'hrrr', 'nbm', 'rrfs'
df_hrrr = load_nwp_data(
    model="rrfs", 
    start_date=date(2021, 2, 20),
)

In [17]:
df_hrrr

Empty DataFrame
Columns: []
Index: []